### ISSUE TITLE
ClassNotFoundException for BambooBlock

### ISSUE THREAD

**Issue by Plokie** [Camotoy/BambooCollisionFix#1]
Attempted to run both
- Official Release build
- Self-build of the latest version using Maven Eclipse

Both times, the Plugin does not load correctly, and the warning `java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.BlockBamboo` is thrown.
This causes the throwing of another warning `java.lang.NullPointerException: Cannot invoke "java.lang.Class.getName()" because "clazz" is null` which then sequentially ends the plugin.

Identified the start of the problem to be coming from Line 18 of NMSReflection.java

Here is a complete log of the event: [https://pastebin.com/ysUTdzsR](https://pastebin.com/ysUTdzsR)

My server jar is Purpur 1.17, so should have bukkit plugin support

My sincerest apologies if this is a fault of my own, I've been at this for hours but couldn't identify how to fix the problem

**Comment by Camotoy** [comment]
Right, I tested Java 16 and not 1.17. Hold on! ^^

**Comment by Plokie** [comment]
No worries! Tysm

**Comment by Camotoy** [comment]
Should now be fixed!
